swagger: "2.0"

info:
    description: Student microservice for mandatory exercise 1
    title: Mandatory exercise 1 (daas, seho, lanc)
    version: 1.0.0
host: "localhost:8080"
schemes:
  - https
  - http
    
paths:  
  /student: 
    get: 
      tags: 
      - "student"
      summary: "Get all students"
      operationId: "getStudents"
      responses: 
        "200":
          description: "OK" 
    post: 
      tags: 
        - "student"
      summary: "Add a student"
      operationId: "addStudent"
      responses: 
        "201":
          description: "OK"
        "405": #not in the go code
          description: "Invalid input"
      
  /student/{studentId}:
    get: 
      tags: 
      - "student"
      description: "This is used to find a student by id"
      summary: "Find a student by id"
      operationId: "getStudentByID"
      parameters: 
      - name: "studentId"
        in: "path"
        description: "ID of student to find"
        required: true
        type: "integer"
        format: "int64"
      responses: 
        "200":
          description: "OK" 
        "404":
          description: "Student not found"
    delete: 
      tags:
      - "student"
      summary: "Deletes a student"
      operationId: "deleteStudentByID"
      parameters: 
      - name: "studentId"
        in: "path"
        description: "ID of student to delete"
        required: true
        type: "integer"
        format: "int64"
      responses: 
        "200":
          description: "Student deleted successfully"
        "404":
          description: "Student not found"
    put: 
      tags:
      - "student"
      summary: "Update a student"
      operationId: "updateStudent"
      parameters: 
      - name: "studentId"
        in: "path"
        description: "ID of student that needs updating"
        required: true
        type: "integer"
        format: "int64"
      - name: "body"
        in: "body"
        description: "The student object with updated information"
        schema: 
          type: object
          required: 
            - ID
            - Name
          properties: 
            ID:
              type: integer
            Name: 
              type: string
            Courses: 
              type: array
              items:
                type: string
      responses: 
        "200":
          description: "OK"
        "400": #a more describing code should be possible to find... 
          description: "Something went wrong" 
          